CREATE DATABASE dbbarbearia;

CREATE TABLE USUARIO (
    USR_COD INT AUTO_INCREMENT PRIMARY KEY,
    USR_CPF VARCHAR(15) UNIQUE NOT NULL,
    USR_NOME VARCHAR(150) NOT NULL,
    USR_EMAIL VARCHAR(100),
    USR_CEL VARCHAR(15),
    USR_LOGIN VARCHAR(100),
    USR_SENHA VARCHAR(50)
);

CREATE TABLE EMPRESA (
	EMP_COD INT AUTO_INCREMENT PRIMARY KEY,
    EMP_CNPJ VARCHAR(19) UNIQUE NOT NULL,
    EMP_NOME VARCHAR(150) UNIQUE NOT NULL,
    EMP_DESC VARCHAR(200),
    EMP_ENDERECO VARCHAR(150)
);

CREATE TABLE FUNCIONARIO (
    FUN_COD INT AUTO_INCREMENT PRIMARY KEY,
    FUN_COD_EMP INT,
    FUN_CPF VARCHAR(15) UNIQUE NOT NULL,
    FUN_NOME VARCHAR(150) NOT NULL,
    FUN_EMAIL VARCHAR(100),
    FUN_CEL VARCHAR(15),
    FUN_LOGIN VARCHAR(100),
    FUN_SENHA VARCHAR(50),
    FOREIGN KEY (FUN_COD_EMP) REFERENCES EMPRESA(EMP_COD)
);

CREATE TABLE AGENDAMENTO(
	AGEND_COD INT AUTO_INCREMENT PRIMARY KEY,
    AGEND_COD_USR INT,
    AGEND_COD_FUN INT,
    AGEND_HORARIO VARCHAR(20) NOT NULL
);