DROP DATABASE BARBERSHOP;

CREATE DATABASE BARBERSHOP;

USE BARBERSHOP;

CREATE TABLE BARBEARIA(
	CODBARBEARIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMESOCIAL VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    TELEFONE1 VARCHAR(15) NOT NULL UNIQUE,
    TELEFONE2 VARCHAR(15) NOT NULL UNIQUE,
    LOGIN VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(30) NOT NULL,
    DESCRICAO TEXT
);

CREATE TABLE ENDERECO(
	CODENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(30) NOT NULL,
    NUMERO VARCHAR(4) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO VARCHAR(30) NOT NULL,
    FK_CODBARBEARIA INT,
    FK_CODCLIENTE INT
);

CREATE TABLE REGRA(
	CODREGRA INT PRIMARY KEY AUTO_INCREMENT,
    REGRA1 VARCHAR(100),
    REGRA2 VARCHAR(100),
    REGRA3 VARCHAR(100),
    REGRA4 VARCHAR(100),
    FK_CODBARBEARIA INT NOT NULL
);

CREATE TABLE CLIENTE(
	CODCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    TELEFONE VARCHAR(30) NOT NULL UNIQUE,
    LOGIN VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(30) NOT NULL
);

CREATE TABLE AGENDAMENTO(
	CODAGENDAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DATA CHAR(11) NOT NULL,
    HORARIO CHAR(6) NOT NULL,
    FK_CODBARBEARIA INT NOT NULL,
    FK_CODCLIENTE INT NOT NULL
);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_BARBEARIA_ENDERECO
FOREIGN KEY (FK_CODBARBEARIA) REFERENCES BARBEARIA(CODBARBEARIA);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_CLIENTE_ENDERECO
FOREIGN KEY (FK_CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE);

ALTER TABLE REGRA ADD CONSTRAINT FK_BARBEARIA_REGRA
FOREIGN KEY (FK_CODBARBEARIA) REFERENCES BARBEARIA(CODBARBEARIA);

ALTER TABLE AGENDAMENTO ADD CONSTRAINT FK_BARBEARIA_AGENDAMENTO
FOREIGN KEY (FK_CODBARBEARIA) REFERENCES BARBEARIA(CODBARBEARIA);

ALTER TABLE AGENDAMENTO ADD CONSTRAINT FK_CLIENTE_AGENDAMENTO
FOREIGN KEY (FK_CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE);